### ISSUE TITLE
Drive Audit: Civic Tech Jobs

### ISSUE THREAD

**Issue by CharityLai6** [hackforla/google-drive-migration#45]
#### Overview
We need to audit the drive so that we can know what files to move and if the receiving end is ready.

### Prerequisite
-  access to the 1Password vault for Google Drive Migration
- know your GitHub username and password so that you can use it in a new browser

#### Prep
For each of the following items, there are instructions in the wiki.  Copy the instruction for next item to be checked off (must do them in order), to a comment below and then complete the item, and hide the comment. 
- [x] [Find Program Area](https://github.com/hackforla/google-drive-migration/wiki/find-program-area)
- [x] [Get Old Drive link](https://github.com/hackforla/google-drive-migration/wiki/get-old-drive-link)
- [ ] [Identify if there are files in the old folder](https://github.com/hackforla/google-drive-migration/wiki/are-there-files-to-move)
- [ ] [Check that drivemigration@ has access to New Google Drive for this project](https://github.com/hackforla/google-drive-migration/wiki/get-access-to-teams-new-google-drive)
- [ ] [Get Project Roster link](https://github.com/hackforla/google-drive-migration/wiki/get-project-roster)

#### Audit
- [ ] [Create Audit Template](https://github.com/hackforla/google-drive-migration/wiki/create-audit-template)
- [ ] [Perform Drive Migration Audit](https://github.com/hackforla/google-drive-migration/wiki/perform-drive-migration-audit)

#### File Moving
- [ ] [Invite file owners to our next file moving party](https://github.com/hackforla/google-drive-migration/wiki/invite-owners-to-move-files)
- [ ] Once file moving party is completed, add a comment about what is outstanding and move to Questions and Review Column

#### Project specific links
2.1 Program Area: Civic Tech Infrastructure
2.2 [Civic Tech Jobs old GDrive]
2.3 [Civic Tech Jobs new GDrive]
2.4 [Civic Tech Jobs Roster]
2.5 [Civic Tech Jobs Drive Migration Audit]
2.6 [older migration template - audit and move info into new template]

**Comment by ExperimentsInHonesty** [comment]
### Find Program Area
- [ ] Open [GDM: Active Project List](https://docs.google.com/spreadsheets/d/1S_g8fHmRhSIXI_VJMVDNdVg1XtN06QoTZtPC1O0GNnw/)
- [ ] Find the Program Area for the project on the spreadsheet (add to resources 2.1)
- [ ] remove the `status: needs program area` label

### If no Program Area found
- [ ] add this comment to your issue
  ```
  I could not find a program area on the spreadsheet for this project
  ```
- [ ] Move the issue to the `Questions/Review` column of the project board

**Comment by ExperimentsInHonesty** [comment]
### Get Old Drive link
- [ ] Go to [HfLA old drive structure](https://drive.google.com/drive/u/0/folders/1mRmBMk6nEvylSOiC7l__XCx5qU3g9w-B)
- [ ] Go into the folder for the projects or community of practices
- [ ] Go into the folder for the Program Area
- [ ] Find the old folder for the project
- [ ] add old drive folder link to resource 2.2
- [ ] remove the `status: needs old drive folder links` label

### If the old folder does not exist
- [ ] add a comment with the text
  ```
  There was no folder for this project in the old drive
  ```
- [ ] add the label `status: old drive not found`
- [ ] unassign yourself from the issue
- [ ] put issue into the Questions/Review column of the project board
