### ISSUE TITLE
Drive Audit: BallotNav

### ISSUE THREAD

**Issue by BCHEN222** [hackforla/google-drive-migration#5]
### Overview
We need to audit the drive so that we can know what files to move and if the receiving end is ready.

### Action Items
- [ ] Audit
   - [ ] start new audit template from copy and add link to resources below
   - [ ] add old drive folder link to resources below 
   - [ ] are there files to move 
   - [ ] if no, close issue as completed
   - [ ] if yes
      - [ ] add new drive location to resources below
      - [ ] use template to identify files to move
      - [ ] is file structure the same (for where the new files go)
- [ ] Engage with product managers
   - [ ] Ask PM to comment their meeting times on this issue 
   - [ ] Show pm demo of file migration and how to use spreadsheet and teach them permissions
   - [ ] Ask product manager if they are able to communicate with old members to get files moved
   - [ ] If yes, then assign them the issue 
   - [ ] Once files moved, close issue with a comment
#### Templates and sources
- [Template for Drive Audit](https://docs.google.com/spreadsheets/d/1uw3SJHe2MOHGaCwbxnanLfqPvggGvLMqBAQloJBNirE/copy)
- [HfLA old drive structure](https://drive.google.com/drive/u/0/folders/1mRmBMk6nEvylSOiC7l__XCx5qU3g9w-B)
 #### Project specific links
- [BallotNav old GDrive](https://drive.google.com/drive/u/0/folders/1vtFG5I0XugZ8eJRdakAzvHUBKFm3CfG5)
- [BallotNav new GDrive](https://drive.google.com/drive/folders/0AJYSE30n7aJaUk9PVA)
- [drive audit spreadsheet](https://docs.google.com/spreadsheets/d/1EBJEevrOlrpG1HOyBN4wKqsFrIl0QU5l6vBCz4MV_Ko/edit#gid=309222957) Still inside project shared drive at the moment, most likely will move to BallotNav shared drive for the PMs
- https://github.com/hackforla/ballotnav/issues/469

**Comment by BCHEN222** [comment]
Copied from today's slack 1 on 1 with stacy 

[Stacey (she/her)](https://app.slack.com/team/U02U9Q5DUF6)
  [1:08 PM](https://hackforla.slack.com/archives/D03LXRHBMF1/p1656360518783259)
Hi Brian- This is Stacey from the BallotNav project. We could use some assistance with our Google Migration issue. We have a few users who we need to work with to move their files, but are having a hard time getting in touch with them. What support can you offer us to help get this done?

[Brian Chen](https://app.slack.com/team/U03LDSPSYTD)
  [1:16 PM](https://hackforla.slack.com/archives/D03LXRHBMF1/p1656361016725409)
Hi Stacy, do you have the Drive Audit Spreadsheet? There is an email template in that spreadsheet that we have had the most success with in terms of reaching out to members, or is there a different problem with reaching out to those members?

[Stacey (she/her)](https://app.slack.com/team/U02U9Q5DUF6)
  [1:36 PM](https://hackforla.slack.com/archives/D03LXRHBMF1/p1656362162920309)
We've mostly been sending messages via the GitHub issue, and it has been being able to stay on top of it with the members who are no longer part of the project. But we have not, as far as I know, tried the email template. What is the Issue number for the Migration, with the checklist of items? We created our own but it might not cover everything that needs to get done. Is there a link to the Audit spreadsheet in that issue?

[Brian Chen](https://app.slack.com/team/U03LDSPSYTD)
  [1:48 PM](https://hackforla.slack.com/archives/D03LXRHBMF1/p1656362899861899)
Hi stacy, I have assigned the issue to you, here is the link : https://github.com/hackforla/google-drive-migration/issues/5  This should have everything you need, and please update your progress in the issue and let us know of any problems so we can help you along.

**Comment by BCHEN222** [comment]
Moved audit spreadsheet in BallotNav shared drive

**Comment by staceyrebekahscott** [comment]
@BCHEN222 Brian- please add @kcoronel to this issue. She is the PM most involved in addressing this for our project, and I want her to be looped in. Thanks.

**Comment by ExperimentsInHonesty** [comment]
When Karen and I meet next time, she and I are going update this issue with the new format and see what our next steps are.

**Comment by ExperimentsInHonesty** [comment]
replaced by issue #65
