### ISSUE TITLE
Video-Making Process: "How to move files you have created"

### ISSUE THREAD

**Issue by CharityLai6** [hackforla/google-drive-migration#59]
### Overview
Create an instructional video (without audio) on how to move files from old project drive folders to the new project drive folders for the Google Drive Migration

### Action Items
- [x] Write a list of steps (instructions) for the video in a document
- [x] Download [Clavier+](https://gryder.org/software/clavier-plus/#download) onto your computer 
   - [x] Create keyboard shortcuts for each individual step
- [x] Sign into drivemigration@ and open Google Drive
   - [x] Create two demo drive folders, one labeled "Demo Shared Drive - OLD" and the other "Demo Shared Drive - NEW"
   - [x] Inside both the old and new demo drive folders, create a folder labeled "Presentation"
   - [x] Inside the folder labeled "Presentation" in both the old and new demo drive folders, create two more folders labeled "Delivered" and "Drafts"
   - [x] Inside the old demo drive, in the "Drafts" folder, create a total of four files (3 created by drivemigration@ & 1 created by Bonnie)
   - [x] Create an audit template for Demo Shared Drive and fill out the spreadsheet accordingly
- [x] Make free [Vimeo](https://vimeo.com/) account using drivemigration@
   - [x] Download [Vimeo Record chrome extension](https://chrome.google.com/webstore/detail/vimeo-record-screen-webca/ejfmffkmeigkphomnpabpdabfddeadcb?hl=en)
- [x] Join Zoom meeting by yourself 
   - [x] Share your entire desktop 
   - [x] Open Zoom chat window on the left side of your screen and open the drive audit spreadsheet for Demo Shared Drive to the right of it
   - [x] Click Vimeo Record in your window's toolbar and begin recording
   - [x] Record yourself demonstrating the file-moving process
- [x] Download free video editing software [Lightworks](https://lwks.com/) and import recording
   - [x] Create pages for the video title, video description, and closing using Google Slides to edit into the video
   - [x] Using [Canva](http://canva.com/), edit specific snapshots of the recording with different shapes and lines to highlight key features in the video
   - [x] Import and edit pieces together into one singular video
   - [x] Upload video from editing software as mp4 onto drivemigration@ Vimeo account
   - [x] Download mp4 onto computer and put video into the Google Drive Migration drive folder

### Resources/Instructions
- ["How to move files you have created" video instructions document](https://docs.google.com/document/d/1XpYoGWaMeyf30n9AK4oLZPSeEVu2IebNH2AZSX_xGzM/edit)
- [Drive Migration Audit: Demo Shared Drive](https://docs.google.com/spreadsheets/d/18HHwkZTP3Nznt_mQW4OKM87JI_gAMFqEyidelOhahr4/edit#gid=590682376)
- [Google Slides - Title, Video Description, & Closing page for video](https://docs.google.com/presentation/d/1pwIyQdqxV0-awvosJ3FGISHDU7Tumeuem3e4FFjAzYs/edit#slide=id.p)
- [Clavier+: Creating keyboard shortcuts](https://gryder.org/software/clavier-plus/#download)
- [Template for Drive Audit](https://docs.google.com/spreadsheets/d/1uw3SJHe2MOHGaCwbxnanLfqPvggGvLMqBAQloJBNirE/copy)
- [Lightworks: free editing software without a watermark](https://lwks.com/)

### Finished Video
- [How to move files you have created](https://vimeo.com/734542825)

**Comment by ExperimentsInHonesty** [comment]
The user/password for Vimeo is in the Google Drive migration 1password vault
